"""Edit group model

Revision ID: 98ee02e29906
Revises: d25d9f32ebc3
Create Date: 2025-05-08 16:32:01.124579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ee02e29906'
down_revision: Union[str, None] = 'd25d9f32ebc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'subjects', ['group_subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'group_subject_id')
    # ### end Alembic commands ###
