"""Edit group model

Revision ID: d25d9f32ebc3
Revises: 737e53cc1816
Create Date: 2025-05-08 12:18:19.323758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25d9f32ebc3'
down_revision: Union[str, None] = '737e53cc1816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_group_subject_id_fkey', 'groups', type_='foreignkey')
    op.drop_column('groups', 'group_subject_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('groups_group_subject_id_fkey', 'groups', 'subjects', ['group_subject_id'], ['id'])
    # ### end Alembic commands ###
