"""Create models

Revision ID: f0ec82b38ead
Revises: fc25dd619b44
Create Date: 2025-04-18 15:07:29.930419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ec82b38ead'
down_revision: Union[str, None] = 'fc25dd619b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('lesson_time', sa.String(), nullable=True),
    sa.Column('lesson_days', sa.String(), nullable=True),
    sa.Column('group_subject', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_firstname', sa.String(), nullable=True),
    sa.Column('student_lastname', sa.String(), nullable=True),
    sa.Column('student_phone_number', sa.String(), nullable=True),
    sa.Column('student_additional_info', sa.Text(), nullable=True),
    sa.Column('student_parents_fullname', sa.String(), nullable=True),
    sa.Column('student_parents_phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_firstname', sa.String(), nullable=True),
    sa.Column('teacher_lastname', sa.String(), nullable=True),
    sa.Column('teacher_phone_number', sa.String(), nullable=True),
    sa.Column('teacher_subject', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_group_association',
    sa.Column('students_id', sa.Integer(), nullable=False),
    sa.Column('groups_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groups_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['students_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('students_id', 'groups_id')
    )
    op.create_table('teacher_group_association',
    sa.Column('teachers_id', sa.Integer(), nullable=False),
    sa.Column('groups_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groups_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['teachers_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teachers_id', 'groups_id')
    )
    op.create_table('teacher_students_association',
    sa.Column('teachers_id', sa.Integer(), nullable=False),
    sa.Column('students_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['students_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teachers_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teachers_id', 'students_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_students_association')
    op.drop_table('teacher_group_association')
    op.drop_table('student_group_association')
    op.drop_table('payment')
    op.drop_table('attendance')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('groups')
    # ### end Alembic commands ###
