"""Add email column to teacher, admin and user sql models

Revision ID: f15d18d3b31c
Revises: 0cafc69b0e84
Create Date: 2025-06-08 22:42:34.975035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15d18d3b31c'
down_revision: Union[str, None] = '0cafc69b0e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('admin_email', sa.String(), nullable=True))
    op.create_index(op.f('ix_admins_admin_email'), 'admins', ['admin_email'], unique=True)
    op.add_column('teachers', sa.Column('teacher_email', sa.String(), nullable=True))
    op.create_index(op.f('ix_teachers_teacher_email'), 'teachers', ['teacher_email'], unique=True)
    op.add_column('user', sa.Column('user_email', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_user_email'), 'user', ['user_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_email'), table_name='user')
    op.drop_column('user', 'user_email')
    op.drop_index(op.f('ix_teachers_teacher_email'), table_name='teachers')
    op.drop_column('teachers', 'teacher_email')
    op.drop_index(op.f('ix_admins_admin_email'), table_name='admins')
    op.drop_column('admins', 'admin_email')
    # ### end Alembic commands ###
